### ISSUE TITLE
Add failure step to build assets workflow to reopen an issue indicating a failure with the workflow

### ISSUE THREAD

**Issue by jeffcharles** [bytecodealliance/javy#391]
## What is the idea?

Add a step to the build assets workflow to reopen a GitHub issue in this repository when the workflow fails.

Something along the lines of:
```
open-issue:
    if: failure()
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: gh issue reopen 53
```

## What problem does it solve?

At the moment, we're not notified when the build assets workflow fails since it just runs on `main` so problems with the that workflow can go undetected. Having an issue the maintainers can follow will mean we get notified when there's a failure with that workflow.
